### ISSUE TITLE
Question. Is there anyway to link a hex to a note?

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [modality/obsidian-text-mapper#1]
This is really fantastic. Can see a number of people interesting in this. I (Josh P) will be looking to do a video on the plugin showcasing its functionality. 

A question I can predict is can you link a hex to a note? Similar to the Obsidian Leaflet functionality. That would be amazing and really allow you to take this all the way.

**Comment by djbrock** [comment]
From a purely theoretical point of view, and having looked at some of the SVG generated by the original, you could wrap the polygon for a hex in an anchor tag and perhaps also make the polygon outline visually distinct. The plugin would need to be modified to read a line like this `0306 soil keep "The Keep|Spooky Keep"` and link the hex to the note 'Spooky Keep'. Or some similar syntax. Then modify the SVG output for anything with a | symbol in the annotation.

**Comment by Alberaan** [comment]
Also interested

**Comment by Dasagriva** [comment]
This would be an awesome feature to have.

**Comment by GandelXIV** [comment]
This could be perfect

**Comment by thattreethatfell** [comment]
> From a purely theoretical point of view, and having looked at some of the SVG generated by the original, you could wrap the polygon for a hex in an anchor tag and perhaps also make the polygon outline visually distinct. The plugin would need to be modified to read a line like this `0306 soil keep "The Keep|Spooky Keep"` and link the hex to the note 'Spooky Keep'. Or some similar syntax. Then modify the SVG output for anything with a | symbol in the annotation.

Yes plz!

**Comment by jamescamber** [comment]
Loving this plugin so far, but linkable hex tiles would be incredible - just popluate a note with all the contents and details of a given tile and link it back to the map for quick easy access? Yes please!

**Comment by vandermore** [comment]
I've added a PR for adding this functionality. The link will appear on the label of the hex.

https://github.com/modality/obsidian-text-mapper/pull/10

**Comment by ObsidianTTRPGProject** [comment]
@modality can we get this reviewed? Sounds fantastic.

**Comment by modality** [comment]
I merged @vandermore's PR. Thanks @vandermore!

**Comment by vandermore** [comment]
> I merged @vandermore's PR. Thanks @vandermore!

No problem. Thanks for the plugin!

**Comment by ObsidianTTRPGProject** [comment]
@vandermore can you push this to a release? I will do another video to let everyone know it can link then.

**Comment by modality** [comment]
@ObsidianTTRPGProject Only I can do that. I have some other fixes and changes going in this weekend and I will create another release then.

**Comment by modality** [comment]
@ObsidianTTRPGProject I have pushed a release which you can find here: https://github.com/modality/obsidian-text-mapper/releases/tag/1.1.0

I had not actually used @vandermore's links yet, but WOW, this is a game changer. Here's a screenshot from a map in my Wolves Upon the Coast campaign. Thanks again!

<img width="500" alt="Screenshot 2024-01-21 at 10 38 48 AM" src="https://github.com/modality/obsidian-text-mapper/assets/179336/ce9b715c-3e8c-4db1-bc56-ab4c27356983">
