### ISSUE TITLE
How to create a link in a label?

### ISSUE THREAD

**Issue by Komiblanka** [modality/obsidian-text-mapper#19]
Hello,

I'm trying the "new" feature of putting a link in a label, but I can't make it work. I'm trying this:
`
``text-mapper
0101 tree "tree"
0102 trees "trees"
0103 forest "forest"
0201 bush [[note name]]|"hola"

# larger label example
other <text x="100" y="1170" font-size="40pt">Small Example</text>
```
The link is to an internal note.

**Comment by Mophs** [comment]
I also assumed the same syntax as you and had the same question. I had a peek at the code and it's all one string that gets split.
The way to get links to work is like so:
`
0606 soil town "Settlement|Village"
`
Where settlement is the name of the page you want to link to and village is the label. You can also append a hashtag and link to headings within.

**Comment by modality** [comment]
@Komiblanka Mophs is correct, thanks Mophs. What I typically do is create a working link in Obsidian. You can link directly to headers too:

```
[[albann-fills#17.12 Desecrated Barrows]]
```

Then copy what's inside the square brackets `[[ ]]` and use it as a label for the hex. The vertical bar `|` can be used to change the label text if the link is particularly unruly:

```
1712 blue-green thorp "albann-fills#17.12 Desecrated Barrows|Desecrated Barrows"
```
